import { Router, type IRouter } from "express";
import healthRouter from "./health";
import summaryRouter from "./summary";
import playersRouter from "./players";
import matchesRouter from "./matches";
import seasonsRouter from "./seasons";
import opponentsRouter from "./opponents";
import managersRouter from "./managers";
import refereesRouter from "./referees";
import miscRouter from "./misc";
import nextMatchRouter from "./next-match";
import birthdaysRouter from "./birthdays";
import adminRouter from "./admin";
import aiImportRouter from "./ai-import";
import ratingsRouter from "./ratings";
import commentsRouter from "./comments";
import suggestionsRouter from "./suggestions";
import transfersRouter from "./transfers";
import presidentsRouter from "./presidents";
import classicoRouter from "./classico";

const router: IRouter = Router();

router.use(healthRouter);
router.use(summaryRouter);
router.use(playersRouter);
router.use(matchesRouter);
router.use(seasonsRouter);
router.use(opponentsRouter);
router.use(managersRouter);
router.use(refereesRouter);
router.use(miscRouter);
router.use(nextMatchRouter);
router.use(birthdaysRouter);
router.use(ratingsRouter);
router.use(commentsRouter);
router.use(suggestionsRouter);
router.use(transfersRouter);
router.use(presidentsRouter);
router.use(classicoRouter);
router.use(adminRouter);
router.use(aiImportRouter);

export default router;
